function isBetaIntStruct = verifyBetaIntStuct( data )

primaryFields = {'Fs', ...
                 'final', ...
                 'prelim', ...
                 'threshold', ...
                 'channel', ...
                 'firstIntervals', ...
                 'noiseIntervals', ...
                 'HVS'};
dataFields = fieldnames(data.betaIntervals);

if all(strcmp(dataFields', primaryFields))
    isBetaIntStruct = 1;
else
    isBetaIntStruct = 0;
end